name = "Sorting"
uuid = "afc248ef-41f1-4986-9fce-3e2a59728464"
authors = ["Gianfranco Ponza <GianProgrammer@yahoo.it>"]
version = "1.0.0"

[compat]
julia = "1.7.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
